// Copyright 2026 Enactic, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Behavior tests for the Unity-LH -> `OpenArm`-workspace pose transform,
//! checked against golden values generated by running the actual upstream
//! `quest_receiver.py` pipeline under numpy 2.4.6 / scipy 1.17.1 (the
//! versions upstream's `pyproject.toml` requires).

// The golden literals below are transcribed verbatim (full precision) from
// the Python-generated reference values for traceability, even where a
// shorter literal would round to the same `f32`, and some happen to be
// close to `FRAC_PI_4` because a 45-degree gripper angle is exact test
// data, not an attempt to approximate that constant.
#![allow(clippy::excessive_precision, clippy::approx_constant)]

use dora_openarm_vr_rust::transform::{
    RawPose, Side, map_trigger_to_gripper, parse_lh_to_rh, pose_to_array, process,
};

const EPS_F32: f32 = 1e-5;
const EPS_F64: f64 = 1e-9;

fn assert_close3(a: [f64; 3], b: [f64; 3]) {
    for i in 0..3 {
        assert!((a[i] - b[i]).abs() < EPS_F64, "index {i}: {a:?} vs {b:?}");
    }
}

fn assert_close4(a: [f64; 4], b: [f64; 4]) {
    for i in 0..4 {
        assert!((a[i] - b[i]).abs() < EPS_F64, "index {i}: {a:?} vs {b:?}");
    }
}

fn assert_close7(a: [f32; 7], b: [f32; 7]) {
    for i in 0..7 {
        assert!((a[i] - b[i]).abs() < EPS_F32, "index {i}: {a:?} vs {b:?}");
    }
}

fn pose(x: f64, y: f64, z: f64, qx: f64, qy: f64, qz: f64, qw: f64) -> RawPose {
    RawPose {
        x,
        y,
        z,
        qx,
        qy,
        qz,
        qw,
    }
}

fn identity_pose(x: f64, y: f64, z: f64) -> RawPose {
    pose(x, y, z, 0.0, 0.0, 0.0, 1.0)
}

#[test]
fn parse_lh_to_rh_flips_z_and_negates_qx_qy_then_normalizes() {
    let (pos, rot) = parse_lh_to_rh(&pose(1.0, 2.0, 3.0, 0.1, 0.2, 0.3, 0.9));
    assert_close3(pos, [1.0, 2.0, -3.0]);
    assert_close4(
        rot.to_xyzw(),
        [
            -0.102_597_835_208_515_41,
            -0.205_195_670_417_030_82,
            0.307_793_505_625_546_2,
            0.923_380_516_876_638_7,
        ],
    );
}

#[test]
fn pose_to_array_reorders_quaternion_to_scalar_first() {
    let (pos, rot) = parse_lh_to_rh(&identity_pose(0.0, 0.0, 0.0));
    let array = pose_to_array(pos, rot);
    // Identity pose -> identity quaternion, scalar-first layout [x,y,z,qw,qx,qy,qz].
    assert_close7(array, [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]);
}

#[test]
fn map_trigger_to_gripper_right_side_golden_values() {
    assert!(
        (map_trigger_to_gripper(0.0, Side::Right) - (-0.785_398_163_397_448_3)).abs() < EPS_F64
    );
    assert!((map_trigger_to_gripper(1.0, Side::Right) - 0.174_532_925_199_432_95).abs() < EPS_F64);
    assert!(
        (map_trigger_to_gripper(0.5, Side::Right) - (-0.305_432_619_099_007_65)).abs() < EPS_F64
    );
}

#[test]
fn map_trigger_to_gripper_left_side_golden_values() {
    assert!((map_trigger_to_gripper(0.0, Side::Left) - 0.785_398_163_397_448_3).abs() < EPS_F64);
    assert!(
        (map_trigger_to_gripper(1.0, Side::Left) - (-0.174_532_925_199_432_95)).abs() < EPS_F64
    );
    assert!((map_trigger_to_gripper(0.5, Side::Left) - 0.305_432_619_099_007_65).abs() < EPS_F64);
}

#[test]
fn map_trigger_to_gripper_clips_below_zero_to_zero() {
    let clipped = map_trigger_to_gripper(-1.0, Side::Right);
    let at_zero = map_trigger_to_gripper(0.0, Side::Right);
    assert!((clipped - at_zero).abs() < EPS_F64);
}

#[test]
fn map_trigger_to_gripper_clips_above_one_to_one() {
    let clipped = map_trigger_to_gripper(2.0, Side::Right);
    let at_one = map_trigger_to_gripper(1.0, Side::Right);
    assert!((clipped - at_one).abs() < EPS_F64);
}

#[test]
fn process_with_no_reference_uses_identity_reference() {
    let right = identity_pose(0.1, 0.2, 0.3);
    let left = identity_pose(-0.1, 0.15, 0.25);

    let outcome = process(None, Some(right), Some(left));

    assert_close7(
        outcome.pose_right.unwrap(),
        [
            0.215_000_003_576_278_7,
            -0.100_000_001_490_116_12,
            0.059_999_998_658_895_49,
            0.707_106_769_084_930_4,
            0.0,
            -0.707_106_769_084_930_4,
            0.0,
        ],
    );
    assert_close7(
        outcome.pose_left.unwrap(),
        [
            0.165_000_006_556_510_93,
            0.100_000_001_490_116_12,
            0.009_999_999_776_482_582,
            0.707_106_769_084_930_4,
            0.0,
            -0.707_106_769_084_930_4,
            0.0,
        ],
    );
    assert!(outcome.pose_reference.is_none());
}

#[test]
fn process_with_reference_rectifies_relative_to_it() {
    let reference = pose(0.05, 0.1, 0.2, 0.0, 0.0, 0.382_683_4, 0.923_879_5);
    let right = pose(0.3, 0.25, 0.4, 0.1, 0.0, 0.0, 0.994_987_4);
    let left = pose(-0.2, 0.1, 0.35, 0.0, 0.2, 0.0, 0.979_795_9);

    let outcome = process(Some(reference), Some(right), Some(left));

    assert_close7(
        outcome.pose_right.unwrap(),
        [
            0.115_000_002_086_162_57,
            -0.282_842_725_515_365_6,
            -0.210_710_674_524_307_25,
            0.715_335_011_482_238_8,
            0.296_301_454_305_648_8,
            -0.584_678_709_506_988_5,
            -0.242_181_837_558_746_34,
        ],
    );
    assert_close7(
        outcome.pose_left.unwrap(),
        [
            0.064_999_997_615_814_21,
            0.176_776_707_172_393_8,
            0.036_776_687_949_895_86,
            0.694_202_125_072_479_2,
            0.134_474_545_717_239_38,
            -0.585_962_891_578_674_3,
            -0.395_787_149_667_739_87,
        ],
    );
    assert_close7(
        outcome.pose_reference.unwrap(),
        [
            0.050_000_000_745_058_06,
            0.100_000_001_490_116_12,
            -0.200_000_002_980_232_24,
            0.923_879_563_808_491_2,
            0.0,
            0.0,
            0.382_683_426_141_738_9,
        ],
    );
}

#[test]
fn process_with_only_right_controller_leaves_left_and_reference_absent() {
    let right = identity_pose(0.5, -0.2, 0.1);

    let outcome = process(None, Some(right), None);

    assert_close7(
        outcome.pose_right.unwrap(),
        [
            0.014_999_999_664_723_873,
            -0.5,
            -0.340_000_003_576_278_7,
            0.707_106_769_084_930_4,
            0.0,
            -0.707_106_769_084_930_4,
            0.0,
        ],
    );
    assert!(outcome.pose_left.is_none());
    assert!(outcome.pose_reference.is_none());
}

#[test]
fn process_with_nothing_present_yields_no_poses() {
    let outcome = process(None, None, None);
    assert!(outcome.pose_right.is_none());
    assert!(outcome.pose_left.is_none());
    assert!(outcome.pose_reference.is_none());
}
